### PR TITLE
add optional --ykhsmauth-reader cmdline option

### PR DESCRIPTION
**Pull request by tarak-stratus**
add optional --ykhsmauth-reader cmdline option for specifying a specific Yubikey reader as identified by ykman list -r

### CODE REVIEW

**Comment by qpernil** [comment]
Rebasing against master will fix the macos failure. There is another pull to replace Ubuntu 18.04 with 22.04 that will fix the other errors (most likely), waiting approval before merging that. So I'd ask you to rebase once https://github.com/Yubico/yubihsm-shell/pull/272 has been merged, so we can see a succesful build. Thx.

**Comment by qpernil** [comment]
Please rebase this pull request against master.

**Comment by tarak-stratus** [comment]
Ok will do it!  Thank you!

**Comment by qpernil** [comment]
Looks like you just made an empty merge commit. You should revert that last commit, perform a git push --force, check out master, perform a git pull, check your branch out again, and finally perform a git rebase master

**Comment by qpernil** [comment]
It looks like you would also need to add the extra argument to the interactive command, see line 518 in src/main.c.'
(As you may know yubihsm-shell can be run interactively or directly from the command line)

**Comment by qpernil** [comment]
Some tests are failing because they lack access to some github secrets, I'll check everything works once I merge.

**Comment by tarak-stratus** [comment]
> Some tests are failing because your fork lacks access to some github secrets, I'll check everything works once I merge.

thank you!  For the interactive use-case, didn't see it essential as there's an operator in control.  The CLI was more for automated front-end where the operator inserts multiple Yubikeys and the script uses meta-data to identify the needed Ykey.  However, will work on the interactive use-case too.

**Comment by qpernil** [comment]
Closing this now as a more complete version is here https://github.com/Yubico/yubihsm-shell/pull/277, and there has been no activity for a while. Thanks for contributing this PR, which inspired the new one!

**Pull request closed without merging**
