### PR TITLE
Support CKA_ALLOWED_MECHANISMS

### PR DESCRIPTION
**Pull request by qpernil**

### CODE REVIEW

**Comment by simo5** [comment]
Two comments here:
* In general CKA_ALOWED_MECHANISM is intended to allow to restrict a key to only perform certain algorithms regardless of what it can do in general. It means it should be a settable attribute when the token has a way to store attributes (and of course it should be validated that all the algorithms set are actually usable. However given the nature of YubiHSM it is understandable if you want this to be a fixed value per key type.
* CKA_ALLOWED_MECHANISMS should not be returned at all if no restrictions are in place. Returning 0 would technically mean no algorithms are supported at all, which generally makes no sense. Any key store would support at least one mechanism.

So given the above the code looks mostly good, except I would make sure to return CKR_ATTRIBUTE_TYPE_INVALID if you do not have a list of allowed mechs for a specific key type.
A good way is to make get_allowed_mechs return a CK_RV and return CKR_ATTRIBUTE_TYPE_INVALID with a final else statement. This will make the code future proof if a new key type is added and someone forgets to add the proper list of restriction in get_allowed_mechs().

Apparently you can then simply ```return get_allowed_mechs(object, value, length);``` in all places where this is used.

**Comment by qpernil** [comment]
The code now reports zero allowed mechanisms if none of the HSM capabilities we check for are set, and only repports CKR_ATTRIBUTE_TYPE_INVALID if the key algorithm is unknown to the get_allowed_mechs function. @simo5 would you let me know if this seems correct ?

**Comment by simo5** [comment]
Does it mean those keys where you report 0 mechanisms are unusable?

**Comment by qpernil** [comment]
Yes unusable through pkcs#11. Ed25519 keys would be an example.

**Comment by simo5** [comment]
It feels odd to show keys that can't be used for anything.
Just FYI, due to an implementation choice in softhsm (which I am arguing is a bug), currently pkcs11-provider has to treat a zero length CKA_ALLOWED_MECHANISMS as "everything allowed", but that will probably get a tunable later on, where it will revert to the (IMO) correct behavior of "nothing" allowed.
In any case, the worst it can happen is that the application will ask to perform a "non allowed" operation, and you will simply return an error as before, no biggie, just some wasted time/calls on the application side.

**Comment by simo5** [comment]
The question I have though is this, will you allow to set the CKA_ALLOWED_MECHANISMS on keys? Like for CKA_ID?

The real use case for CKA_ALLOWED_MECHANISMS is to restrict what mechanism the token will allow to use with a specific key.

For example on creation of an RSA key the application can restrict its use just to all or some of the PSS mechanisms and deny PKCS1.5 mechanisms by setting CKA_ALLOWED_MECHANISMS to a specific list of mechanisms.

Setting is not enough of course, it would also require enforcement at time of use of those mechanisms. It is not hard to do this in the driver, but I wonder if you have space to store this data and an easy way to lookup at when operation like signature are requested.

**Comment by qpernil** [comment]
One could argue that it is doing that now, sort of - The allowed mechanisms will be based of the capabilities that the particular key has, so it can vary from key to key depending on what was set on the key when created. As with other attributes it cannot be changed on an existing key (excepting the new meta-attributes, which are not really handled by the HSM), and it is enforced by the HSM already that you cant perform operations without the capability for it. What you can do will actually usually be less because the authentication key may not allow all operations the target key allows. So setting of the attribute would be something else, like the meta-attributes, and wouldn't currently be enforced by the HSM.

**Comment by simo5** [comment]
Perhaps you can then interpret the CKA_ALLOWED_METHODS on a template when C_GenerateKeyPair is called to fine tune the HSM capabilities for a key ?

Capabilitis are less fine-grained but it wouldn't be a bad start.

I see you can set sign-pss vs sign-pkcs but it doesn't see you can say something like 
just CKM_SHA384_RSA_PKCS_PSS and not other hash variant with capabilities. That's where storing the mechanisms list (if provided at key creation) would help (assuming in driver and not in-HSM enforcement for the more fine grained restrictions).

**Comment by qpernil** [comment]
@simo5 can I ask for your feedback if the current implementation, that only returns CKR_ATTRIBUTE_TYPE_INVALID for unsupported key types, and not for an empty list, is more correct than the previous one that returned that for an empty list ? 
My reasoning is that a supported key that actually doesn't allow any of the mechanisms we support through pkcs#11 should in fact return an empty list.

**Comment by qpernil** [comment]
Regarding settable attributes Im doubtful it is particularly useful, as we would have to set capabilities that are not as fine grained, thus implicitly setting other allowed mechanisms. So I'd like to just merge this as is, if you find it useful.

**Comment by simo5** [comment]
I think this patch is already useful as is.
As I said I have to ignore empty lists, but then if an operation is attempted, and it is not supported,, the token will return an error, so no biggie.

**Comment by simo5** [comment]
Btw the idea of interpreting CKA_ALLOWED_MECHANISMS at key generation was that you would turn it into the less fine grained capabilities, and create a key with those capabilities. You can then ignore storing the actual set, just keep generating it as you do now.

The usefulness is in being able to generate, say a RSA key, that are allowed to only do signatures, but not encryption, etc..
But up to you, it is not a huge deal.

**Pull request merged**
