### PR TITLE
Additional curl options

### PR DESCRIPTION
**Pull request by OsterlaD**
Add support for libcurl cert and key to use client-side certificates as authentication.
Add support for shell like variable expansion.
Add libcurl noproxy option.

### CODE REVIEW

**Comment by qpernil** [comment]
If you rebase this branch now I expect it will turn green

**Comment by qpernil** [comment]
The build failures are tests that are failing because your PR doesn't have access to our test devices.

On the PR itself we are reluctant to accept the inclusion of the wordexp function, which could be used for privilege elevation style attacks if an attacker puts a configuration in place that performs script evaluation.

**Comment by OsterlaD** [comment]
Thanks for the explanation. What does this mean for the MR? Are you going to close it?

**Comment by qpernil** [comment]
We would like to accept it without the wordexp functionality, please let us know if that is essential to your use case.

**Comment by OsterlaD** [comment]
It is just convenience. It allows to share the config file with something like `key = ~/my.key`.
I will push without this patch.

**Review by qpernil — APPROVED** [review]

**Pull request merged**
